# Generated by Django 4.0.2 on 2022-03-04 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalution',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouring.student', verbose_name='کد دانشجو'),
        ),
    ]
